export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

import { NextResponse } from 'next/server';
import type PDFDocumentType from 'pdfkit';
import { sql } from '@/app/lib/db';
import { verifyPayToken } from '@/app/lib/pay-link';
import { formatDateToLocal } from '@/app/lib/utils';
import {
  getCompanyProfileForInvoiceWorkspace,
  MissingInvoiceWorkspaceError,
} from '@/app/lib/public-branding';
import {
  enforceRateLimit,
  parseRouteParams,
  routeTokenParamsSchema,
} from '@/app/lib/security/api-guard';

const PDFDocument = require('pdfkit/js/pdfkit.standalone') as typeof PDFDocumentType;

function formatAmountForPdf(amountCents: number) {
  const value = amountCents / 100;
  return `${value.toFixed(2)} EUR`;
}

async function buildInvoicePdf(input: {
  invoice: {
    id: string;
    customer_name: string;
    customer_email: string;
    status: string;
    date: string;
    due_date: string | null;
    amount: number;
    invoice_number: string | null;
    description: string | null;
  };
  company: {
    companyName: string;
    address: string;
    companyEmail: string;
  };
}) {
  return new Promise<Buffer>((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const invoiceLabel = input.invoice.invoice_number ?? input.invoice.id.slice(0, 8);
    doc.fontSize(22).text(input.company.companyName || 'Lateless', 50, 60);
    doc.fontSize(14).text(`Invoice ${invoiceLabel}`, 50, 92);

    doc.moveDown(2);
    doc.fontSize(12).text('From');
    if (input.company.address) doc.text(input.company.address);
    if (input.company.companyEmail) doc.text(`Email: ${input.company.companyEmail}`);

    doc.moveDown();
    doc.fontSize(12).text('To');
    doc.text(input.invoice.customer_name);
    doc.text(input.invoice.customer_email);

    doc.moveDown();
    doc.fontSize(12).text(`Date: ${formatDateToLocal(input.invoice.date)}`);
    doc.text(`Due date: ${input.invoice.due_date ? formatDateToLocal(input.invoice.due_date) : '—'}`);
    doc.text(`Status: ${input.invoice.status}`);
    doc.text(`Amount: ${formatAmountForPdf(input.invoice.amount)}`);
    if (input.invoice.description) {
      doc.moveDown(0.5);
      doc.text(`Description: ${input.invoice.description}`);
    }

    doc.fontSize(10).fillColor('#444444').text('Generated by Lateless', 50, 760, { width: 500 });
    doc.end();
  });
}

export async function GET(
  req: Request,
  props: { params: Promise<{ token: string }> },
) {
  const rateLimitResponse = await enforceRateLimit(
    req,
    {
      bucket: 'public_invoice_pdf',
      windowSec: 60,
      ipLimit: 30,
    },
    {
      failClosed: true,
    },
  );
  if (rateLimitResponse) {
    return rateLimitResponse;
  }

  const rawParams = await props.params;
  const parsedParams = parseRouteParams(routeTokenParamsSchema, rawParams);
  if (!parsedParams.ok) {
    return parsedParams.response;
  }
  const params = parsedParams.data;
  const verification = verifyPayToken(params.token);
  if (!verification.ok) {
    return NextResponse.json({ error: 'Invalid payment link.' }, { status: 404 });
  }

  const [invoice] = await sql<{
    id: string;
    amount: number;
    status: string;
    date: string;
    due_date: string | null;
    invoice_number: string | null;
    description: string | null;
    customer_name: string;
    customer_email: string;
    workspace_id: string | null;
    user_email: string | null;
  }[]>`
    select
      i.id,
      i.amount,
      i.status,
      i.date,
      i.due_date,
      i.invoice_number,
      i.description,
      c.name as customer_name,
      c.email as customer_email,
      i.workspace_id,
      i.user_email
    from public.invoices i
    join public.customers c on c.id = i.customer_id
    where i.id = ${verification.payload.invoiceId}
    limit 1
  `;

  if (!invoice) {
    return NextResponse.json({ error: 'Invoice not found.' }, { status: 404 });
  }

  let branding: Awaited<ReturnType<typeof getCompanyProfileForInvoiceWorkspace>>;
  try {
    branding = await getCompanyProfileForInvoiceWorkspace({
      invoiceId: invoice.id,
      workspaceId: invoice.workspace_id,
      userEmail: invoice.user_email,
    });
  } catch (error) {
    if (error instanceof MissingInvoiceWorkspaceError) {
      return NextResponse.json({ error: 'Invoice not found.' }, { status: 404 });
    }
    throw error;
  }

  const companyAddress = [
    branding.addressLine1,
    branding.addressLine2,
    branding.city,
    branding.country,
  ]
    .map((value) => value?.trim())
    .filter(Boolean)
    .join(', ');

  const pdfBuffer = await buildInvoicePdf({
    invoice,
    company: {
      companyName: branding.companyName || 'Lateless',
      address: companyAddress,
      companyEmail: branding.billingEmail,
    },
  });
  const filenameId = invoice.invoice_number ?? invoice.id;

  return new NextResponse(pdfBuffer, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="invoice-${filenameId}.pdf"`,
      'Cache-Control': 'no-store, max-age=0',
    },
  });
}
